version: '2'    # docker-compose.yml 파일의 명세 버전으로 버전에 따라 지원하는 도커 엔진 버전 다름
services:       # 컨테이너 이름 설정, 여기서는 db, wordpress 두 개의 이름 사용
 db:
  image: mariadb:10.9       # 말 그대로 컨테이너의 사용 할 이름과 태그, image 속성 대신 build 속성도 사용함
  volumes:                       # 마운트하려는 디렉토리
   - ./mysql:/var/lib/mysql      # {호스트 디렉토리} : {컨테이너 디렉토리}
  restart: always                 # 재시작 정책
  environment:                      # 컨테이너에서 사용할 환경변수들
    MYSQL_ROOT_PASSWORD: wordpress    # 환경변수 : 값
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress
 wordpress:
  image: wordpress:latest
  volumes:
    - ./wp:/var/www/html
  ports:                    # 컨테이너와 연결할 포트
    - "8000:80"             # {호스트 포트} : {컨테이너 포트}
  restart: always
  environment:
    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_PASSWORD: wordpress
    WORDPRESS_DB_USER: wordpress    # 추가해야 wordpress <=> db connect error 발생 안함