version: '2'    # docker-compose.yml 파일의 명세 버전으로 버전에 따라 지원하는 도커 엔진 버전 다름
services:
 db:
  image: mariadb:10.9
  volumes:
   - ./mysql:/var/lib/mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: wordpress
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress
 wordpress:
  image: wordpress:latest
  volumes:
    - ./wp:/var/www/html
  ports:
    - "8000:80"
  restart: always
  environment:
    WORDPRESS_DB_HOST: db:3306
    WORDPRESS_DB_PASSWORD: wordpress
    WORDPRESS_DB_USER: wordpress    # 추가해야 wordpress <=> db connect error 발생 안함