### Exam 1. php 컨테이너 만들기, docker-compose 이용
### 현재 php 컨테이너의 경우 웹 서버가 아닌 단순한 cli 명령어이기에 출력된 후 종료 된다
version: '2'
services:
  php:
    image: php:7
    volumes:
     - ./hello.php:/app/hello.php
    command:    # php file 실행하는 명령어
      php /app/hello.php  