# $ cd vote
# $ docker build -t voting-vote .
# $ cd worker
# $ docker build -t voting-worker .
# $ cd result
# $ docker build -t voting-result .

# error 발생 시점 전에 밑에 명령어 추가해줘야된다
# RUN echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list
#   참고 https://www.sysnet.pe.kr/2/0/13331

version: '3'   
services: 
  vote:
    image: voting-vote
    ports:
      - "60001:80"
  
  redis:
    image: redis:alpine
  
  worker:
    image: voting-worker
  
  db:
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  result:
    image: voting-result
    ports:
      - "60002:80"