version: '3'

services:   # 여기서 listen port를 8000으로 사용한 것, front, back 같은 포트 사용한다는 것이 X
            # route 규칙에 8000 호출 시 front로 가는 설정이 존재
  frontend:
    image: subicura/guestbook-frontend:latest
    restart: always
    ports:
      - "62000:8000"
    environment:
      PORT: 8000
      GUESTBOOK_API_ADDR: backend:8000

  backend:
    image: subicura/guestbook-backend:latest
    restart: always
    environment:
      PORT: 8000
      GUESTBOOK_DB_ADDR: mongodb:27017

  mongodb:
    image: mongo:4
